volumes:
  postgres_volume:

services:
  pg:
    image: postgres:17.5-alpine3.21
    environment:
      - "POSTGRES_DB=${PG_DB_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/home/dak/Programming/databases/postgres/chat-service-temp

  migrator:
    build:
      context: database/postgres
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB-HOST: pg

  server:
    build:
      context: cmd/server
      dockerfile: server.Dockerfile
    ports:
      - "50052:50052"